services:
  api:
    container_name: api
    build: api
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    container_name: db
    build: db
    ports:
      - 6379:6379
    volumes:
      - ./data:/data